- name: check latest release
  uri:
    url: https://api.github.com/repos/containerd/nerdctl/releases/latest
    return_content: true
  no_log: true
  register: json_response

- name: get release download url
  ansible.builtin.debug:
    var: item
  loop: "{{ json_response.json | community.general.json_query(release_query) }}"
  vars:
    release_query: "assets[?contains(name,'linux-amd64')&&contains(name,'full')].browser_download_url"
  register: nerdctl_release_url

- name: download release
  get_url:
    url: "{{ url }}"
    dest: "{{ ansible_env.HOME }}/{{ url | urlsplit('path') | regex_search('[^/]+$') }}"
  vars:
    url: "{{ nerdctl_release_url.results[0].item }}"
  register: archive_path

- name: extract archive
  become: true
  unarchive:
    src: "{{ archive_path.dest }}"
    dest: /usr/local
    remote_src: yes

- name: install systemd-container needed for rootless
  become: true
  apt:
    name: systemd-container
    state: latest

- name: install dbus thing  # probably not needed
  become: true
  apt:
    name: dbus-user-session
    state: latest

- name: install RootlessKit
  become: true
  apt:
    name: rootlesskit
    state: latest

- name: install slirp4netns
  become: true
  apt:
    name: slirp4netns
    state: latest

# I haven't figured out how this works yet
# The big tar.gz should bring all dependencies, but seems we have to install more
# stuff, or at least finish some steps manually
# We may also need to start some services
# systemctl --user start containerd.service
# sudo loginctl enable-linger danielf
# There's also an error with cni and cgroup2

      #- name: install buildkit
      #  shell: containerd-rootless-setuptool.sh install-buildkit
      #  become: true
      #  become_user: danielf
      #  become_method: machinectl
      #
      #- name: install rootless
      #  shell: containerd-rootless-setuptool.sh install
      #  become: true
      #  become_user: danielf
      #  become_method: machinectl


